### ISSUE TITLE
Broken README file

### ISSUE THREAD

**Issue by ulfryk** [varanthir/to-do#5]
It now shows:

> ToDo in this project: [x] local storage [x] add new note, with UI (button 'Add', form) [x] delete note [x] modify note [x] note nice UI

but should:

**ToDo in this project:**

- [ ] local storage 
- [ ] add new note, with UI (button 'Add', form) 
- [ ] delete note 
- [ ] modify note 
- [ ] note nice UI

**Comment by varanthir** [comment]
Thx :) Me didn't know it's possible.
Readme fixed.
